apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx-yaml
    another: lable
  name: mynginx-yaml
spec:
  containers:
    - image: nginx
      name: mynginx-yaml
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
