set backup
set backupdir=~/vimfiles/tmp//
set directory=~/vimfiles/tmp//

call plug#begin()
"Add plugins here and run :PlugInstall or :PlugUpdate
"https://github.com/junegunn/vim-plug?tab=readme-ov-file#usage
Plug 'morhetz/gruvbox'
Plug 'pprovost/vim-ps1'
call plug#end()

colorscheme gruvbox
set ruler
set hlsearch
set lines=100 columns=200

filetype plugin on

set tabstop=4
set shiftwidth=4
set softtabstop=0
set noexpandtab
set noautoindent
set nosmartindent
set nocindent

set relativenumber
set hlsearch

autocmd FileType ps1 setlocal indentexpr= indentkeys=
"Highlight end-of-line whitespace
autocmd BufRead,BufNewFile * match Error /\s\+$/

"Map // to search for selected text. From https://vim.fandom.com/wiki/Search_for_visually_selected_text#Simple
vnoremap // y/\V<C-R>=escape(@",'/\')<CR><CR>
