set backup
set backupdir=~/vimfiles/tmp//
set directory=~/vimfiles/tmp//

call plug#begin()
"Add plugins here and run :PlugInstall or :PlugUpdate
"https://github.com/junegunn/vim-plug?tab=readme-ov-file#usage
Plug 'morhetz/gruvbox'
Plug 'pprovost/vim-ps1'
Plug 'pedrohdz/vim-yaml-folds'
call plug#end()

colorscheme gruvbox
set ruler
set hlsearch
set lines=100 columns=200

filetype plugin on
syntax on

set tabstop=4
set shiftwidth=4
set softtabstop=0
set noexpandtab
set noautoindent
set nosmartindent
set nocindent

set relativenumber
set hlsearch

"Enable syntax folding for XML files, but start with foldsopen
let g:xml_syntax_folding = 1
autocmd FileType xml setlocal foldmethod=syntax
autocmd FileType xml :%foldopen!

autocmd FileType ps1 setlocal indentexpr= indentkeys=

"YAML setup: https://www.arthurkoziel.com/setting-up-vim-for-yaml/
"YAML files need space indents
autocmd FileType yaml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab foldlevel=1

"Highlight end-of-line whitespace
autocmd BufRead,BufNewFile * match Error /\s\+$/

"Map // to search for selected text. From https://vim.fandom.com/wiki/Search_for_visually_selected_text#Simple
vnoremap // y/\V<C-R>=escape(@",'/\')<CR><CR>

"Add support for % to jump between xml/html tags
packadd! matchit
